### ISSUE TITLE
Maybe post about this on the Sponge forums?

### ISSUE THREAD

**Issue by parlough** [ustc-zzzz/hocon-colorizer#1]
I know many people in the community use VS Code, so they would probably be quite happy to know about an up-to-date syntax plugin made by someone else in the community! 

Keep up the good work :>

**Comment by ustc-zzzz** [comment]
In fact, I didn't want to post about it in the Sponge Forum until most of the features are implemented. However, it seems that many people want to use it, so I finally decided to post about it in advance.

<https://forums.spongepowered.org/t/hocon-colorizer-a-vscode-extension-for-language-syntax-highlighting-of-hocon/23618>
